#!/bin/sh

set -e

unit=rustdesk.service

case "$1" in
    purge)
        deb-systemd-helper purge "$unit" >/dev/null
        rm -rf -- /root/.config/RustDesk /root/.config/rustdesk
        ;;
esac

exit 0
