#!/bin/sh

set -e

unit=rustdesk.service
service=rustdesk

case "$1" in
    purge)
        deb-systemd-helper purge "$unit" >/dev/null
        update-rc.d "$service" remove >/dev/null
        rm -rf -- /root/.config/RustDesk /root/.config/rustdesk
        ;;
esac

case "$1" in
    remove|purge)
        if [ -d /run/systemd/system ]; then
            /bin/systemctl --system daemon-reload >/dev/null
        fi
        ;;
esac

exit 0
