#!/bin/sh

set -e

unit=rustdesk.service
unit_path=/usr/lib/systemd/system/rustdesk.service

if [ "$1" = configure ]; then

	ln -f -s /usr/share/rustdesk/rustdesk /usr/bin/rustdesk

	rm -f /etc/systemd/system/rustdesk.service
	rm -f /usr/lib/systemd/system/rustdesk.service
	rm -f /usr/lib/systemd/user/rustdesk.service
	mkdir -p /usr/lib/systemd/system
	cp /usr/share/rustdesk/files/systemd/rustdesk.service "$unit_path"
	deb-systemd-helper enable "$unit" >/dev/null
	deb-systemd-invoke daemon-reload >/dev/null
	deb-systemd-invoke start "$unit" >/dev/null
fi

exit 0
