#!/bin/sh

set -e

unit=rustdesk.service
service=rustdesk

if [ "$1" = configure ]; then

	update-rc.d "$service" defaults >/dev/null
	if [ -d /run/systemd/system ]; then
		deb-systemd-helper enable "$unit" >/dev/null
		/bin/systemctl --system daemon-reload >/dev/null
		deb-systemd-invoke start "$unit" >/dev/null
	else
		invoke-rc.d "$service" start >/dev/null
	fi
fi

exit 0
