#!/bin/sh

set -e

unit=rustdesk.service

case "$1" in
    install|upgrade)
        deb-systemd-invoke stop "$unit" >/dev/null || true
        sleep 1
        rm -f /usr/bin/libsciter-gtk.so
        ;;
esac

exit 0
