#!/bin/sh

set -e

unit=rustdesk.service

case "$1" in
    remove|upgrade|deconfigure)
        deb-systemd-invoke stop "$unit" >/dev/null
        if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
            deb-systemd-helper disable "$unit" >/dev/null
        fi
        rm -f /usr/bin/rustdesk
        rm -f /etc/systemd/system/rustdesk.service
        rm -f /usr/lib/systemd/system/rustdesk.service
        rm -f /usr/lib/systemd/user/rustdesk.service
        /bin/systemctl --system daemon-reload >/dev/null
        ;;
esac

exit 0
